INSERT INTO category (category_name) VALUES ('American');
INSERT INTO category (category_name) VALUES ('Italian');
INSERT INTO category (category_name) VALUES ('Mexican');
INSERT INTO category (category_name) VALUES ('Fast Food');
INSERT INTO unit_of_measure (uom) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (uom) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (uom) VALUES ('Cup');
INSERT INTO unit_of_measure (uom) VALUES ('Pinch');
INSERT INTO unit_of_measure (uom) VALUES ('Ounce');
INSERT INTO unit_of_measure (uom) VALUES ('Each');
INSERT INTO unit_of_measure (uom) VALUES ('Dash');
INSERT INTO unit_of_measure (uom) VALUES ('Pint');
INSERT INTO unit_of_measure (uom) VALUES ('Piece');
-- SELECT * FROM CATEGORY;
-- SELECT * FROM ingredient;
-- SELECT * FROM notes;
-- SELECT * FROM recipe;
-- SELECT * FROM unit_of_measure;